gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@14.21.3 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/pavithara/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pavithara/Documents/GIT/IM/Intain testnetwork/intain-markets-node-app/node_modules/peer-id/node_modules/ursa-optional/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pavithara/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pavithara/.cache/node-gyp/14.21.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pavithara/.cache/node-gyp/14.21.3',
gyp info spawn args   '-Dnode_gyp_dir=/home/pavithara/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pavithara/.cache/node-gyp/14.21.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pavithara/Documents/GIT/IM/Intain testnetwork/intain-markets-node-app/node_modules/peer-id/node_modules/ursa-optional',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
In file included from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/home/pavithara/.cache/node-gyp/14.21.3/include/node/node.h:793:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  793 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/pavithara/.cache/node-gyp/14.21.3/include/node/node.h:827:3: note: in expansion of macro ‘NODE_MODULE_X’
  827 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/ursaNative.cc:389:1: note: in expansion of macro ‘NODE_MODULE’
  389 | NODE_MODULE(ursaNative, init)
      | ^~~~~~~~~~~
make: execvp: touch: Operation not permitted
make: *** [ursaNative.target.mk:111: Release/obj.target/ursaNative/src/ursaNative.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pavithara/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 5.15.0-101-generic
gyp ERR! command "/home/pavithara/.nvm/versions/node/v14.21.3/bin/node" "/home/pavithara/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pavithara/Documents/GIT/IM/Intain testnetwork/intain-markets-node-app/node_modules/peer-id/node_modules/ursa-optional
gyp ERR! node -v v14.21.3
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok 
